### ISSUE TITLE
US 1 - Create a database in MongoDB and Read data

### ISSUE THREAD

**Issue by hdkuzmahashmi** [hdkuzmahashmi/capstone-smartSaver#1]
## Value proposition
As a user
I want to utilize the Smart Saver App to access and manage my expenses easily.
In order to save my expenses.

## Description

![US1_Database](https://github.com/hdkuzmahashmi/capstone-smartSaver/assets/76174247/3ae1abce-46c2-41b1-98c0-17fadf02acc1)
![US1_Read](https://github.com/hdkuzmahashmi/capstone-smartSaver/assets/132385633/5a2ab0ec-a65d-4a28-9894-06016b79a834)

## Acceptance criteria
- [x] User can see a list of expenses with a title, their expense in their chosen currency and a sum of all expenses
- [ ] User can see, that different colors stand for different categories. These colors are seen in a circle before every expense

## Tasks
- [x] Create a database in MongoDB.
- [x] Develop a Schema and a Collection in MongoDB.
- [x] Configure Local Environment Variables.
- [x] Establish a connection to MongoDB.
- [x] Implement Mongoose to create a Schema.
- [x] Create three collections: categories, expense entries, and currencies.
- [x] Add dummy data to above collections.
- [x] Create API Folder and add RESTful Route for Read (folder Structure: /api/..).
- [x] Create API to fetch data from database, using SWR.
- [x] Create List-detail component to show title, category and amount.
- [x] Create List component to loop through List-detail component to display expenses in the list page.

**Comment by NikRoe** [comment]
US will be updated as we agreed on in the Sprint Planning

**Comment by maryhbb** [comment]
update is done!

**Comment by NikRoe** [comment]
Hi there,

only having the database without showing your users any data, does not really have a benefit.

You should extend your user story:
- your db should contain some dummy data (5-10 entries is enough)
- the dummy data should be displayed when the user opens the app

If you wish to split this up into 2 user stories:
- the first US could be: work with local dummy data to start with and display it in your app. 
- the second US could be: integrate the database and move the dummy data there.

**Comment by NikRoe** [comment]
Hi there,

your tasks look good 👌 

In the Acceptance Criteria, however, you should be more specific as to what is being displayed:

I see a list of expenses in the drawing with a circle (for categories?), a title and the value. You should mention this in the AC.
I also see a sum at the end of the list. You should also mention this in the AC.

How are the categories and the entries connected? Will you the color correspond to a certain category? Will users already be able to set categories?
This is not clear to me yet and you should try be explicit regarding the behaviour of your app.

Best regards 👋
