### ISSUE TITLE
US10 - Filter Expenses

### ISSUE THREAD

**Issue by willywdev** [hdkuzmahashmi/capstone-smartSaver#16]
## Value proposition
As a user, I want to filter expenses by price, category, date and alphabetically in the Expense Tracker. This makes it easy to find and analyze my expenses, simplifying financial management.

## Description
We're adding a handy filtering feature to the Expense Tracker. You'll be able to sort expenses by price, whether from lowest to highest or highest to lowest. Plus, you can filter by category to find what you're looking for even faster. Additionally sort it by date or alphabetically.

When you use the filter, the results will show up right away. We're making sure it's easy to use and understand.

<img width="491" alt="US_Filter" src="https://github.com/hdkuzmahashmi/capstone-smartSaver/assets/135379190/38e67058-6bf7-42ce-96ae-1a43e3e0e7dd">

## Acceptance criteria
- [ ] There should be a user interface element to initiate the filtering process.
- [ ] Users should be able to select between ascending and descending order for price filtering.
- [ ] Users should be able to choose a specific category to filter expenses.
- [ ] Filtered results should be displayed promptly and reflect the selected criteria accurately.
- [ ] The filter options should be intuitive and user-friendly.

## Tasks
- [ ] Design and integrate a user interface element for initiating the filtering process.
- [ ] Implement logic for sorting expenses by price in both ascending and descending order.
- [ ] Develop a mechanism for filtering expenses by category, date and alphabetically
- [ ] Ensure filtered results are displayed correctly in the Expense Tracker interface.
