### ISSUE TITLE
US 2 - Add Expense

### ISSUE THREAD

**Issue by hdkuzmahashmi** [hdkuzmahashmi/capstone-smartSaver#2]
## Value proposition
As a user,
I want to add my own expense,
in order to track my expenses in different categories. 

## Description
![US2_Create (1)](https://github.com/hdkuzmahashmi/capstone-smartSaver/assets/132385633/13099d37-2cb9-470f-8dcc-5a5bc4e0e131)

## Acceptance criteria
- [ ] User can go back to the Homepage through a small Button, which has an Arrow in it
- [ ] User can add new expense as per different categories.
- [ ] User can choose a title, a category, the amount (of currency) and a small description
- [ ] The Categories are seen in a Drop-Down-Menu. 
- [ ] Each Category has a colored Circle and a Category Name
- [ ] There is a Submit Button which has the Plus-Sign in it
- [ ] User can see their created expense right after he clicked the Submit Button
- [ ] If the user doesn't submit any data, an error message is seen.
- [ ] The first three fields are required to be filled out. The description is optional

## Tasks
- [x] Create a feature branch
- [x] Create an Expense (Form) Component
- [x] Implement a Post Rest Method in Api
- [x] Implement Fetch Api for Post data and navigate to the List page

**Comment by NikRoe** [comment]
Hi there,

this looks promising!

You don't need to mention that the expense will be added to the database in the value proposition.

Have you worked with Cloudinary already? Otherwise I suggest extracting the feature of uploading bills to a separate user story.

For the Acceptance Criteria I was wondering what would happen if a user tried submitted a new expense and did not fill out all input fields. Would that be possible or a some fields mandatory?

You will most likely create the new expenses with a form component, mentioning this in the Tasks makes sense.

Best regards 👋

**Comment by NikRoe** [comment]
LGTM
