### ISSUE TITLE
US 3 - Edit Expense

### ISSUE THREAD

**Issue by hdkuzmahashmi** [hdkuzmahashmi/capstone-smartSaver#3]
## Value proposition
As a user,
I want to be able to edit any expenses,
so that I can make changes to it.

## Description
![US3_Update (1)](https://github.com/hdkuzmahashmi/capstone-smartSaver/assets/132385633/d0805778-77a3-44e6-8c20-9b74d8c44170)

## Acceptance criteria
- [ ] User can edit any expense through a small button, which has a Pencil in it (signalling editable content)
- [ ] On clicking the Edit Button, the user is sent to a form
- [ ] The Edit-Form includes all the data of the editable expense the user chose
- [ ] There is a Submit Button, which has an Icon in it, signalling to change the Expense Data
- [ ] When clicking on Submit Button the user is sent to the List VIew of his Content, instantly seeing the changes the user has made

## Tasks
- [ ] Create a feature branch
- [ ] Use the Expense (Form) Component for Editing expense as well. 
- [ ] Implement a Put RESTful API Route 
- [ ] Send data from Frontend to API
- [ ] Navigate to the List page, after data is created

**Comment by NikRoe** [comment]
Hi there,

nice start!

I would change the value proposition to:

> As a user,
> I want to be able to edit any expenses,
> so that I can make changes to it.

In case you will have implemented Cloudinary in a previous user story, it makes sense to have the attach-file option, otherwise, you should remove that part from the AC.

In your last Task I am not sure what you mean with the "Fetch Api for Post data".
I would most likely just remove the whole line.

Best regards 👋

**Comment by NikRoe** [comment]
LGTM
