### ISSUE TITLE
US 4 - Delete Expense

### ISSUE THREAD

**Issue by hdkuzmahashmi** [hdkuzmahashmi/capstone-smartSaver#4]
## Value proposition
As a user,
i want to delete any expense,
incase i dont want to show a specific expense anymore or i wrongfully created an expense

## Description
![US4_Delete (1)](https://github.com/hdkuzmahashmi/capstone-smartSaver/assets/132385633/0591147e-bcdf-47bf-82f3-2bbbe3e8ad8e)

## Acceptance criteria
- [x] User can delete any expense through a Delete Button.
- [x] The Delete Button is small. It has a Trashcan Icon in it, signalling to delete the expense
- [x] The Delete Button is visible on every expense
- [x] When clicking on the Delete Button a Modal (small window) appears, asking the user for confirmation, if he is sure about the Deletion Process
- [x] In this Confirmation-Modal the User can choose if he is sure (Delete Button in Red) or Cancel the Deletion of his Expense (Cancel-Button in normal color)

## Tasks
- [ ] Create a feature branch
- [ ] Use the List Component to write logic for deleting expense. 
- [ ] Remove uploaded images(bills) from Cloudinary.
- [ ] Implement a Delete Rest Method in Api
- [ ] Implement Fetch Api to delete data from database.
- [ ] When the delete button show the alter message to confirm from User( Are you sure you want to delete this entry?).

**Comment by NikRoe** [comment]
Hi there,

this looks good to me.

As in previous user stories I am wondering about Cloudinary. In case this will not have been implemented until this US, you should remove it from this US. Otherwise you can of course keep it.

Best regards 👋
