### ISSUE TITLE
US19-1 Save Uploaded Receipt Url

### ISSUE THREAD

**Issue by hdkuzmahashmi** [hdkuzmahashmi/capstone-smartSaver#49]
## Value proposition
As a user, I want the ability to save the uploaded receipt/image URL in the Database for easy retrieval and association with each expense entry.

## Description
Building upon the feature of uploading receipts in the application, we are introducing the capability to save the URL of the uploaded image. This will facilitate seamless association between uploaded receipts and corresponding expense entries.

## Acceptance criteria
- [ ] Upon successful image upload, the system should securely save the URL and other expense details.

## Tasks
- [ ] Implement logic to save the uploaded image URL and other expense details in the database.
- [ ] Implement ExpenseImages collection to add multiple image URLs along with ExpenseId.
