### ISSUE TITLE
US 5 - Layout

### ISSUE THREAD

**Issue by hdkuzmahashmi** [hdkuzmahashmi/capstone-smartSaver#5]
## Value proposition
As a user,
I want to see, add, edit and delete my expenses in a more visual appealing way,
so that using the App is fun to me.

## Description
![US5_Layout2](https://github.com/hdkuzmahashmi/capstone-smartSaver/assets/132385633/28b8f2c7-f4dd-4f6b-aaf6-7a15346b9b39)

## Acceptance criteria
- [ ] User should be able to see Header and footer.
- [ ] In the Header there is a logo on the left side
- [ ] In the footer there is a Create Button and a Back Button (if needed).
- [ ] The Create Button changes its appearance, depending on the site, the user is on (On Edit-Page: An Icon resembling an Edit Stage - neutral color, On Home-Page: A Plus-Icon with a neutral backgrand, On Create-Page: A Plus-Icon with a green background) 
- [ ] User should be able to navigate all Pages through Links
- [ ] User can also see Sum of all expenses on Home page.
- [ ] When deleting an expense, the background is colored in a red kind of color.

## Tasks
- [ ] Create a feature branch to implement layout
- [ ] Create Layout Component
- [ ] Create Header and Footer Component and call in Layout Component
- [ ] Implement user friendly layout using Styled Component

**Comment by NikRoe** [comment]
Hi there,

nice start!

Whenever something is a placeholder for a feature that is supposed to come at a later point, this placeholder should be removed and not be part of the wireframe.

>  In the Header there is a placeholder avatar icon and our logo on the left side and a "Three Buttons"-Component which opens a modal for Register and Login

You will most likely not have a login by the time you start implementing this user story, you can therefore remove the 3 Buttons used to open the modal.
Moreover, you will most likely be implementing a login using NextAuth which enables your App to use OAuth, it will look different than what is currently displayed in the wireframe.

> The Create Button changes its appearance, depending on the site, the user is on

How will the Create Button change its appearance? Will it receive a different color for highlighting?

> User should be able to navigate all Pages through Buttons

Your users will navigate mostly through links that you will style to appear as buttons, I assume.

Best regards 👋

**Comment by NikRoe** [comment]
LGTM
