### ISSUE TITLE
US 6 - Detail Page

### ISSUE THREAD

**Issue by hdkuzmahashmi** [hdkuzmahashmi/capstone-smartSaver#6]
### Value proposition
As a User,
I want to be able to click on any expense in the list,
so that I can view the details of a particular expense and have the option to edit or delete it.

### Description
![US6_DetailPage](https://github.com/hdkuzmahashmi/capstone-smartSaver/assets/39566862/23fcce81-7091-4fa2-930c-ef5827ef79aa)

### Acceptance criteria
- [ ] User can click on any row in the list and be redirected to the detail page.
- [ ] The detail page should display the data of the particular Expense (Title, Description, Category, and Amount) along with three buttons: Edit, Delete, and Back.
- [ ] If the user didn't provide a description, the description title should not be shown.
- [ ] The Delete button should prompt a confirmation message (Are you sure you want to delete this entry?).
- [ ] If the user takes an action by clicking a Link, they should be redirected to the respective site (Back, Edit, Delete).

### Tasks
- [ ] Create a feature branch.
- [ ] Implement a dynamic GET API Route for every expense in the backend.
- [ ] Set up a dynamic Next.js Route with a variable ID in the frontend.
- [ ] Retrieve the ID of the expense using Next Router.
- [ ] Fetch data for the expense by ID from the Database / API using swr.
- [ ] Create the DetailExpense Component to display data for a particular Expense with three buttons: Edit, Delete, and Back.
- [ ] Link the Component and dynamic Next.js Route with the rest of the app.

**Comment by alhen002** [comment]
Hello, 
nice acceptance criteria! I really like your idea and i am looking forward to your implementation. Please add some more tasks and be a bit more detailed on that. :)

all the best

Alex

**Comment by NikRoe** [comment]
LGTM
